# Generated by Django 6.0.3 on 2026-03-31 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_perfilusuario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.CharField(choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=2)),
                ('anio', models.PositiveIntegerField(default=2026)),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Administración')),
                ('otros_cargos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Otros Cargos/Multas')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Mora', 'En Mora')], default='Pendiente', max_length=20)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario')),
            ],
            options={
                'verbose_name': 'Cuenta de Cobro',
                'verbose_name_plural': 'Cuentas de Cobro',
            },
        ),
    ]
