# Generated by Django 6.0.3 on 2026-03-31 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        ('usuarios', '0003_remove_perfilusuario_apartamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentacobro',
            options={},
        ),
        migrations.RemoveField(
            model_name='cuentacobro',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='cuentacobro',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='cuentacobro',
            name='otros_cargos',
        ),
        migrations.RemoveField(
            model_name='cuentacobro',
            name='residente',
        ),
        migrations.AddField(
            model_name='cuentacobro',
            name='apartamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.apartamento', verbose_name='Apartamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='anio',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='mes_referencia',
            field=models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='valor_base',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
