# Generated by Django 6.0.3 on 2026-03-31 01:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_alter_cuentacobro_options_and_more'),
        ('usuarios', '0004_alter_apartamento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentacobro',
            options={'verbose_name': 'Cuenta de Cobro', 'verbose_name_plural': 'Cuentas de Cobro'},
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='anio',
            field=models.IntegerField(default=2026, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='mes_referencia',
            field=models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='valor_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Administración Mes'),
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Convivencia', 'Convivencia'), ('Ruido', 'Ruido'), ('Mascotas', 'Mascotas'), ('Escombros', 'Escombros'), ('Otros', 'Otros')], max_length=20)),
                ('descripcion', models.TextField(verbose_name='Motivo de la sanción')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Multa')),
                ('fecha_suceso', models.DateField(default=django.utils.timezone.now)),
                ('aplicada_en_cobro', models.BooleanField(default=False, verbose_name='Ya facturada?')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.apartamento', verbose_name='Apartamento')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
            },
        ),
    ]
