# Generated by Django 6.0.3 on 2026-04-08 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_alter_cuentacobro_options_alter_cuentacobro_anio_and_more'),
        ('usuarios', '0005_apartamento_codigo_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionCartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gestion', models.CharField(choices=[('Llamada Telefonica', 'Llamada Telefonica'), ('Carta Notificatoria', 'Carta Notificatoria'), ('WhatsApp / Mensaje', 'WhatsApp / Mensaje'), ('Acuerdo de Pago', 'Acuerdo de Pago Presencial'), ('Visita', 'Visita Domiciliaria'), ('Otro', 'Otro')], max_length=50)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones o Acuerdo')),
                ('acuerdo_pago', models.BooleanField(default=False, verbose_name='¿Generó Acuerdo de Pago?')),
                ('fecha_compromiso', models.DateField(blank=True, null=True, verbose_name='Fecha Compromiso de Pago')),
                ('estado_acuerdo', models.CharField(blank=True, choices=[('Pendiente', 'Acuerdo Pendiente de Fecha'), ('Cumplido', 'Acuerdo Cumplido Exitosamente'), ('No Cumplido', 'Incumplió Promesa')], max_length=20, null=True)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='finanzas/gestiones/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones_cartera', to='usuarios.apartamento')),
                ('gestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gestor / Auxiliar de Cobranza')),
            ],
            options={
                'verbose_name': 'Gestión de Cartera',
                'verbose_name_plural': 'Gestiones de Cartera',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
