# Generated by Django 6.0.3 on 2026-04-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_gestioncartera'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacobro',
            name='valor_abonado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Abonado'),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='valor_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Facturado'),
        ),
    ]
