# Generated by Django 6.0.3 on 2026-04-13 23:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_add_valor_abonado'),
        ('usuarios', '0008_apartamento_saldo_a_favor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestioncartera',
            name='tipo_gestion',
            field=models.CharField(choices=[('Llamada Telefonica', 'Llamada Telefónica'), ('Carta Notificatoria', 'Carta Notificatoria'), ('WhatsApp / Mensaje', 'WhatsApp / Mensaje'), ('Acuerdo de Pago', 'Acuerdo de Pago Presencial'), ('Visita', 'Visita Domiciliaria'), ('Otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='multa',
            name='aplicada_en_cobro',
            field=models.BooleanField(default=False, verbose_name='¿Ya facturada?'),
        ),
        migrations.CreateModel(
            name='Recaudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Recaudado')),
                ('fecha_recaudo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('categoria', models.CharField(choices=[('Administracion', 'Administración'), ('Multa', 'Multa'), ('Reserva', 'Reserva'), ('Otro', 'Otro')], default='Administracion', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de Pago (Consignación/Transferencia)')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.apartamento', verbose_name='Apartamento')),
            ],
            options={
                'verbose_name': 'Recaudo',
                'verbose_name_plural': 'Recaudos',
                'ordering': ['-fecha_recaudo'],
            },
        ),
    ]
