# Generated by Django 6.0.3 on 2026-03-31 02:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_alter_apartamento_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportadora', models.CharField(help_text='Ej: Servientrega, Envia, Amazon', max_length=50)),
                ('destinatario', models.CharField(max_length=100, verbose_name='Nombre en el paquete')),
                ('guia', models.CharField(blank=True, max_length=50, verbose_name='Número de Guía')),
                ('fecha_recepcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('Recibido', 'Recibido en Portería'), ('Notificado', 'Residente Notificado'), ('Entregado', 'Entregado al Residente'), ('Devuelto', 'Devuelto a Transportadora')], default='Recibido', max_length=20)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('quien_recoge', models.CharField(blank=True, help_text='Nombre de quien retira el paquete', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.apartamento', verbose_name='Apto Destino')),
                ('recibido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correspondencia',
                'verbose_name_plural': 'Correspondencia (Paquetes)',
            },
        ),
    ]
