# Generated by Django 6.0.3 on 2026-04-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0002_paquete_entregado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='transportadora',
            field=models.CharField(help_text='Ej: Servientrega, Envía, Amazon', max_length=50),
        ),
    ]
