# Generated by Django 6.0.3 on 2026-04-08 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Documento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Corta')),
                ('categoria', models.CharField(choices=[('Manual', 'Manual de Convivencia'), ('Reglamento', 'Reglamento Interno'), ('Planos', 'Planos y Estructuras'), ('Circulares', 'Circulares Informativas'), ('Formatos', 'Formatos Descargables'), ('Otro', 'Otro Documento')], default='Otro', max_length=50)),
                ('archivo', models.FileField(upload_to='documentos_generales/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Archivo PDF')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
