# Generated by Django 6.0.3 on 2026-03-31 02:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Aviso')),
                ('contenido', models.TextField(verbose_name='Cuerpo del Mensaje')),
                ('prioridad', models.CharField(choices=[('Baja', 'Informativo'), ('Media', 'Importante'), ('Alta', 'Urgente / Alerta')], default='Baja', max_length=10)),
                ('segmentacion', models.CharField(choices=[('Todas', 'Todas las Torres'), ('Torre 1', 'Torre 1'), ('Torre 2', 'Torre 2'), ('Torre 3', 'Torre 3'), ('Torre 4', 'Torre 4')], default='Todas', max_length=20)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='comunicados/pdfs/')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Publicado')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados y Noticias',
            },
        ),
    ]
