# Generated by Django 6.0.3 on 2026-03-31 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Peticion', 'Petición'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia')], default='Queja', max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(verbose_name='Detalle de la solicitud')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('respuesta_admin', models.TextField(blank=True, null=True, verbose_name='Respuesta de la Administración')),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('En Proceso', 'En Proceso'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=20)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'PQRS',
                'verbose_name_plural': 'PQRS (Quejas y Reclamos)',
            },
        ),
    ]
