# Generated by Django 6.0.3 on 2026-03-31 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_alter_apartamento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Visitante')),
                ('documento', models.CharField(max_length=20, verbose_name='Cédula/ID')),
                ('tipo_vehiculo', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Carro', 'Carro'), ('Moto', 'Moto')], default='Ninguno', max_length=20)),
                ('placa', models.CharField(blank=True, max_length=10, verbose_name='Placa')),
                ('parqueadero_visitante', models.CharField(blank=True, max_length=10, verbose_name='Cupo Asignado')),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Programado', 'Programado'), ('En Sitio', 'En Sitio'), ('Salida', 'Salida')], default='Programado', max_length=20)),
                ('apartamento_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.apartamento', verbose_name='Apto Destino')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.perfilusuario')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Control de Visitantes',
            },
        ),
    ]
