# Generated by Django 6.0.3 on 2026-03-31 01:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_apartamento_options_and_more'),
        ('visitantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitante',
            options={'verbose_name': 'Control de Acceso', 'verbose_name_plural': 'Control de Acceso (Portería)'},
        ),
        migrations.RenameField(
            model_name='visitante',
            old_name='fecha_ingreso',
            new_name='hora_ingreso_real',
        ),
        migrations.RenameField(
            model_name='visitante',
            old_name='fecha_salida',
            new_name='hora_salida_real',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='parqueadero_visitante',
        ),
        migrations.AddField(
            model_name='visitante',
            name='cupo_asignado',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='visitante',
            name='fecha_programada',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='visitante',
            name='motivo_visita',
            field=models.CharField(blank=True, help_text='Ej: Reparación, Entrega paquete', max_length=100),
        ),
        migrations.AddField(
            model_name='visitante',
            name='observaciones_vigilancia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitante',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_porteria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitante',
            name='tipo_visitante',
            field=models.CharField(choices=[('Familiar', 'Familiar'), ('Domiciliario', 'Domiciliario'), ('Técnico', 'Técnico'), ('Proveedor', 'Proveedor'), ('Ocasional', 'Visitante Ocasional')], default='Ocasional', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='apartamento_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.apartamento'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='documento',
            field=models.CharField(max_length=20, verbose_name='Documento/ID'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='estado',
            field=models.CharField(choices=[('Programado', 'Programado'), ('Dentro', 'En Sitio / Dentro'), ('Salió', 'Salió'), ('Cancelado', 'Cancelado'), ('No llegó', 'No llegó')], default='Programado', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='placa',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('Ninguno', 'Ninguno'), ('Carro', 'Carro'), ('Moto', 'Moto'), ('Bicicleta', 'Bicicleta')], default='Ninguno', max_length=20),
        ),
    ]
