# Generated by Django 6.0.3 on 2026-04-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0002_alter_visitante_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='foto_visitante',
            field=models.ImageField(blank=True, null=True, upload_to='visitantes/', verbose_name='Fotografía'),
        ),
    ]
