# Generated by Django 6.0.3 on 2026-04-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0003_visitante_foto_visitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='autorizado_por_nombre',
            field=models.CharField(blank=True, max_length=150, verbose_name='Voz de Autorización (Nombre)'),
        ),
    ]
