# Generated by Django 6.0.3 on 2026-03-30 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN_SISTEMA', 'Administrador del Sistema'), ('ADMIN_CONJUNTO', 'Administrador del Conjunto'), ('RESIDENTE', 'Residente / Propietario'), ('VIGILANCIA', 'Vigilancia')], default='RESIDENTE', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
