# Generated by Django 6.0.3 on 2026-03-30 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Ficha de Usuario', 'verbose_name_plural': 'Fichas de Usuarios'},
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='contacto_emergencia',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Cuenta Activa'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='apartamento',
            field=models.CharField(default='Pendiente', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='documento',
            field=models.CharField(default='Pendiente', max_length=20, unique=True, verbose_name='Número de Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='email_personal',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='emergencia_nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre de Emergencia'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='emergencia_parentesco',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='emergencia_telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono de Emergencia'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre_completo',
            field=models.CharField(default='Administrador Inicial', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='observaciones',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='permitir_acceso_portal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='recibir_notificaciones',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_ocupacion',
            field=models.CharField(choices=[('Propietario', 'Propietario'), ('Arrendatario', 'Arrendatario'), ('Familiar', 'Familiar del Propietario')], default='Propietario', max_length=20),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='torre',
            field=models.CharField(default='General', max_length=10, verbose_name='Torre / Bloque'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Sistema'),
        ),
    ]
