# Generated by Django 6.0.3 on 2026-03-31 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfilusuario_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='apartamento',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='torre',
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torre', models.CharField(max_length=10, verbose_name='Torre / Bloque')),
                ('numero', models.CharField(max_length=10, verbose_name='Número de Apartamento')),
                ('piso', models.PositiveIntegerField(verbose_name='Piso')),
                ('residente_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartamentos_asignados', to='usuarios.perfilusuario')),
            ],
            options={
                'verbose_name': 'Apartamento',
                'verbose_name_plural': 'Apartamentos',
                'unique_together': {('torre', 'numero')},
            },
        ),
    ]
