# Generated by Django 6.0.3 on 2026-03-31 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_perfilusuario_apartamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartamento',
            options={'ordering': ['torre', 'numero'], 'verbose_name': 'Apartamento', 'verbose_name_plural': 'Apartamentos'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'ordering': ['nombre_completo'], 'verbose_name': 'Ficha de Usuario', 'verbose_name_plural': 'Fichas de Usuarios'},
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='residente_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartamentos_asignados', to='usuarios.perfilusuario', verbose_name='Residente Principal'),
        ),
    ]
