# Generated by Django 6.0.3 on 2026-04-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_apartamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='codigo_pago',
            field=models.CharField(blank=True, help_text='Ej: 14501', max_length=20, null=True, unique=True, verbose_name='Código Bancario CSV'),
        ),
    ]
