# Generated by Django 6.0.3 on 2026-04-09 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_apartamento_codigo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='inquilino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrendamientos_asignados', to='usuarios.perfilusuario', verbose_name='Inquilino / Arrendatario'),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades_asignadas', to='usuarios.perfilusuario', verbose_name='Propietario Legal'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='primer_ingreso',
            field=models.BooleanField(default=True, verbose_name='¿Es su primer ingreso?'),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='residente_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartamentos_asignados', to='usuarios.perfilusuario', verbose_name='Residente Principal (LEGACY)'),
        ),
        migrations.CreateModel(
            name='Ocupante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('documento', models.CharField(blank=True, max_length=20)),
                ('parentesco', models.CharField(help_text='Ej: Esposa, Hijo, Madre', max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('es_menor_edad', models.BooleanField(default=False)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitantes', to='usuarios.apartamento')),
            ],
            options={
                'verbose_name': 'Ocupante',
                'verbose_name_plural': 'Censo: Ocupantes',
            },
        ),
    ]
