# Generated by Django 6.0.3 on 2026-04-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_apartamento_inquilino_apartamento_propietario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocupante',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
    ]
