# Generated by Django 6.0.3 on 2026-04-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_ocupante_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='saldo_a_favor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo a Favor ($)'),
        ),
    ]
