# Generated by Django 6.0.3 on 2026-03-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PQRS', 'Petición, Queja, Reclamo o Sugerencia'), ('MANTENIMIENTO', 'Solicitud de Reparación')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Abierto', max_length=20)),
            ],
        ),
    ]
