# Generated by Django 6.0.3 on 2026-03-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='prioridad',
            field=models.CharField(choices=[('Baja', 'Baja - Rutinario'), ('Media', 'Media - Importante'), ('Alta', 'Alta - Urgente')], default='Media', max_length=10),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('Abierto', 'Abierto / Pendiente'), ('En Proceso', 'En Revisión'), ('Cerrado', 'Resuelto / Finalizado')], default='Abierto', max_length=20),
        ),
    ]
