# Generated by Django 6.0.3 on 2026-03-30 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0002_solicitud_prioridad_alter_solicitud_estado'),
        ('usuarios', '0002_alter_perfilusuario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Peticion', 'Petición'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia'), ('Mantenimiento', 'Mantenimiento'), ('Seguridad', 'Seguridad'), ('Convivencia', 'Convivencia')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], default='Media', max_length=10)),
                ('zona_afectada', models.CharField(choices=[('Apartamento', 'Apartamento'), ('Zona Comun', 'Zona Común'), ('Parqueadero', 'Parqueadero'), ('Porteria', 'Portería')], default='Apartamento', max_length=20)),
                ('ubicacion_especifica', models.CharField(blank=True, max_length=100)),
                ('area_responsable', models.CharField(choices=[('Admin', 'Administración'), ('Mantenimiento', 'Mantenimiento'), ('Seguridad', 'Seguridad'), ('Aseo', 'Aseo')], default='Admin', max_length=20)),
                ('asignado_a', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('En Proceso', 'En Proceso'), ('Pendiente Residente', 'Pendiente Residente'), ('Resuelto', 'Resuelto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('imagen_evidencia', models.ImageField(blank=True, null=True, upload_to='comunicaciones/evidencias/')),
                ('observaciones_internas', models.TextField(blank=True)),
                ('respuesta_residente', models.TextField(blank=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario')),
            ],
            options={
                'verbose_name': 'Comunicación / PQRS',
                'verbose_name_plural': 'Comunicaciones / PQRS',
            },
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
