# Generated by Django 6.0.3 on 2026-03-31 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0003_comunicacion_delete_solicitud'),
        ('usuarios', '0004_alter_apartamento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Comunicación / PQRS', 'verbose_name_plural': 'Comunicaciones / PQRS'},
        ),
        migrations.AlterField(
            model_name='comunicacion',
            name='asignado_a',
            field=models.CharField(blank=True, max_length=100, verbose_name='Personal encargado'),
        ),
        migrations.AlterField(
            model_name='comunicacion',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción detallada'),
        ),
        migrations.AlterField(
            model_name='comunicacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reporte'),
        ),
        migrations.AlterField(
            model_name='comunicacion',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Límite de Respuesta'),
        ),
        migrations.AlterField(
            model_name='comunicacion',
            name='imagen_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='comunicaciones/evidencias/', verbose_name='Foto de Evidencia'),
        ),
        migrations.AlterField(
            model_name='comunicacion',
            name='observaciones_internas',
            field=models.TextField(blank=True, verbose_name='Notas de la Administración'),
        ),
        migrations.AlterField(
            model_name='comunicacion',
            name='respuesta_residente',
            field=models.TextField(blank=True, verbose_name='Respuesta final al residente'),
        ),
        migrations.AlterField(
            model_name='comunicacion',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones', to='usuarios.perfilusuario', verbose_name='Residente Solicitante'),
        ),
        migrations.AlterField(
            model_name='comunicacion',
            name='tipo',
            field=models.CharField(choices=[('Peticion', 'Petición'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia'), ('Mantenimiento', 'Mantenimiento'), ('Seguridad', 'Seguridad'), ('Convivencia', 'Convivencia')], max_length=20, verbose_name='Tipo de Solicitud'),
        ),
        migrations.AlterField(
            model_name='comunicacion',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título/Asunto'),
        ),
        migrations.AlterField(
            model_name='comunicacion',
            name='ubicacion_especifica',
            field=models.CharField(blank=True, help_text='Ej: Torre A Apto 101 o Salón Social', max_length=100),
        ),
    ]
