# Generated by Django 6.0.3 on 2026-04-08 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0004_alter_comunicacion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaPQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(verbose_name='Cuerpo de la Respuesta')),
                ('evidencia', models.ImageField(blank=True, null=True, upload_to='comunicaciones/respuestas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_pqrs_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Autor de Respuesta')),
                ('comunicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='comunicacion.comunicacion')),
            ],
        ),
    ]
