# Generated by Django 6.0.3 on 2026-04-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0005_respuestapqrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicacion',
            name='numero_radicado',
            field=models.CharField(blank=True, help_text='Generado automáticamente al crear la solicitud. Ej: PQRS-2026-000001', max_length=25, null=True, unique=True, verbose_name='Número de Radicado'),
        ),
    ]
