# Generated by Django 6.0.3 on 2026-03-30 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_maxima', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('residente_nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.zonacomun')),
            ],
        ),
    ]
