# Generated by Django 6.0.3 on 2026-03-30 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_perfilusuario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_comun', models.CharField(choices=[('Salón', 'Salón Social'), ('BBQ', 'Zona BBQ'), ('Piscina', 'Piscina')], max_length=50)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('asistentes', models.PositiveIntegerField(verbose_name='Número de asistentes')),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('estado_reserva', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('aprobado_por', models.CharField(blank=True, max_length=100, verbose_name='Administrador que aprueba')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado_pago', models.BooleanField(default=False, verbose_name='¿Está pagado?')),
                ('requiere_aseo', models.BooleanField(default=False)),
                ('inventario_entregado', models.BooleanField(default=False)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario', verbose_name='Residente que solicita')),
            ],
        ),
    ]
