# Generated by Django 6.0.3 on 2026-03-30 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_profesional_v1'),
        ('usuarios', '0002_alter_perfilusuario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario', verbose_name='Residente que solicita'),
        ),
    ]
