# Generated by Django 6.0.3 on 2026-04-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reserva_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='comprobante_pago',
            field=models.ImageField(blank=True, null=True, upload_to='reservas/pagos/', verbose_name='Recibo o Comprobante de Transacción'),
        ),
    ]
