# Generated by Django 6.0.3 on 2026-04-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_comprobante_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='comprobante_pago',
            field=models.FileField(blank=True, null=True, upload_to='reservas/pagos/', verbose_name='Recibo o Comprobante de Transacción'),
        ),
    ]
