# Generated by Django 6.0.3 on 2026-04-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_comprobante_filefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(choices=[('Salón', 'Salón Social'), ('BBQ', 'Zona BBQ'), ('Piscina', 'Piscina')], max_length=50, unique=True, verbose_name='Zona Común')),
                ('valor', models.DecimalField(decimal_places=0, default=0, help_text='Valor que debe pagar el residente por el uso de esta zona.', max_digits=10, verbose_name='Tarifa de Uso ($)')),
                ('deposito_garantia', models.DecimalField(decimal_places=0, default=0, help_text='Valor reembolsable condicionado al buen uso del espacio.', max_digits=10, verbose_name='Depósito de Garantía ($)')),
                ('descripcion', models.TextField(blank=True, help_text='Capacidad, horarios, condiciones especiales, etc.', verbose_name='Descripción / Condiciones')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Disponible para reservas?')),
            ],
            options={
                'verbose_name': 'Tarifa de Zona',
                'verbose_name_plural': 'Tarifario de Zonas Comunes',
                'ordering': ['zona'],
            },
        ),
    ]
