# Generated by Django 6.0.3 on 2026-04-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_add_tarifa_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='zona_comun',
            field=models.CharField(choices=[('salon', 'Salón Social'), ('bbq', 'Zona BBQ'), ('piscina', 'Piscina')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tarifazona',
            name='zona',
            field=models.CharField(choices=[('salon', 'Salón Social'), ('bbq', 'Zona BBQ'), ('piscina', 'Piscina')], max_length=50, unique=True, verbose_name='Zona Común'),
        ),
    ]
