# Generated by Django 6.0.3 on 2026-04-14 04:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_reserva_zona_comun_alter_tarifazona_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de Reserva (Uso)'),
        ),
    ]
